[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.deps]
script = '''
cargo install wasm-bindgen-cli --version 0.2.81
npm install
'''

[tasks.build-server]
script = '''
cargo build --release
wasm-bindgen --out-dir ./packages/app/assets/wasm --target web --typescript ./target/wasm32-unknown-unknown/release/demo_lsp_browser.wasm
'''

[tasks.build-app]
script = '''
npm run build --workspace=packages/app
'''

[tasks.build-app-vscode]
dependencies = ["build-server"]
script = '''
npm run compile-web --workspace=packages/app-vscode
'''

[tasks.build]
dependencies = ["build-server", "build-app"]

[tasks.clean-server]
script = '''
cargo clean
'''

[tasks.clean-app]
script = '''
rm -rf packages/app/dist
rm -rf packages/app/assets/wasm
'''

[tasks.clean]
dependencies = ["clean-server", "clean-app"]

[tasks.format]
script = '''
cargo +nightly fmt --all
'''

[tasks.run]
script = '''
npm run app --workspace=packages/app
'''

[tasks.run-app-vscode]
dependencies = ["build-app-vscode"]
script = '''
npm run run-in-browser --workspace=packages/app-vscode
'''
